= Diagnóstico
Antes de entrar al análisis previo de la subsidiaria, se identifican diversos factores críticos que condicionan su desempeño actual y futuro. En primer lugar, la planeación deficiente aparece como uno de los principales obstáculos. Estudios internos reflejan que "los principales obstáculos para la mejora son la mala planificación y el mal control"@fn6. En el sector construcción, esto se traduce en la necesidad urgente de contar con cronogramas de obra más precisos, como los diagramas de Gantt, así como una adecuada planificación de la demanda por zonas. Estas prácticas permiten optimizar recursos, reducir costos asociados y mejorar la productividad@fn2.

Asimismo, el control de inventarios se ha mostrado inadecuado en diferentes experiencias, afectando el flujo de materiales y recursos. Por ejemplo, en la concesión Talara de Cosapi se detectó un "déficit en su gestión de almacén de materia prima", lo que provocaba una baja productividad@fn6. De manera general, se advierte que la mala gestión de la cadena de suministro origina sobrecostos, desperdicio de materiales y la necesidad de retrabajos, factores que afectan directamente los márgenes de los proyectos.

Por otro lado, se observa una comunicación e integración fragmentada entre las distintas áreas y contratistas. Esta falta de integración produce silos informativos que generan problemas de coordinación, retrasos y sobrecostos@fn7. Estudios indican que aproximadamente el 70% de los proyectos sufre demoras principalmente por esta falta de coordinación entre equipos@fn7, revelando que las ineficiencias logísticas tienen su raíz en una comunicación deficiente.

El uso limitado de tecnologías avanzadas constituye otro aspecto que impacta negativamente. A nivel global, se estima que el sector construcción pierde alrededor de USD 177.000 millones anuales debido al uso de procesos y tecnologías obsoletas@fn7. Aunque Cosapi ha demostrado esfuerzos por innovar mediante la adopción de metodologías como VDC e industrialización para digitalizar y automatizar proyectos, cualquier retraso o resistencia en la implementación de estas herramientas puede intensificar los problemas logísticos y de comunicación.

Finalmente, los riesgos contractuales también representan un elemento sensible a considerar. En proyectos como la Línea 2 del Metro de Lima, donde participa Cosapi, se han establecido cláusulas de cofinanciamiento estatal y exclusiones del riesgo de demanda durante la concesión@fn9. Estas disposiciones buscan minimizar la incertidumbre contractual; sin embargo, cualquier incumplimiento en los plazos de ejecución o en el suministro de materiales podría acarrear penalidades y renegociaciones contractuales, afectando la estabilidad y el flujo del proyecto.

== Micro Entorno
El micro entorno de Cosapi Concesiones se configura a partir de relaciones estrechas con clientes clave, proveedores estratégicos y competidores con capacidad internacional. La empresa opera principalmente en proyectos de transporte, infraestructura hídrica y concesiones viales, donde la dinámica de la demanda regional, los ciclos de licitación y las exigencias de contenido local influyen directamente en su cadena de valor. Además, la estructura de costos, los plazos de pago y la participación en consorcios multimodales determinan la flexibilidad operativa de la unidad. Factores como la concentración de proveedores nacionales, la estacionalidad de obras y la disponibilidad de financiamiento acotan el margen de maniobra en la planificación y ejecución de proyectos.

#strong(text(15.5pt, "Fortalezas"))\

La posición competitiva de Cosapi Concesiones, dentro de un mercado exigente y diversificado, conlleva diversas ventajas, traducidas en fortalezas al momento de buscar la licitación de una obra pública. Esto se logra gracias a la estandarización de sus procesos, alianzas a largo plazo y un fuerte poder económico. Desarrollando estos puntos:

- #strong("Experiencia y reputación consolidada: ") Se apoya en la vasta trayectoria de su matriz en grandes proyectos de infraestructura y minería. Ha participado con éxito en obras de compañías como Antamina, Cerro Verde, Toquepala y Quellaveco#footnote[COSAPI: Cosapi presente en la Expo San Juan Minera en Argentina. (s. f.). https://www.cosapi.com.pe/Site/Index.aspx?aID=2663#:~:text=Cosapi%20tiene%20una%20vasta%20experiencia,Toromocho].  Este prestigio le da acceso a consorcios internacionales de primer nivel (Iridium, Vialia-FCC, Webuild, Hitachi, etc.)#footnote[COSAPI S.A. (s. f.-c). Memoria Integrada 2023. https://www.cosapi.com.pe/Upload/documento/misc/cosapimemoria_integrada_2023vf.pdf#:~:text=Metro%20de%20Lima%20L%C3%ADnea%202,el]<fn8> y a una amplia red de proveedores de calidad. De hecho, la propia empresa destaca que su “prestigio y buena imagen le dan acceso a los mejores socios, proveedores y colaboradores”#footnote[COSAPI concesiones. (s. f.). https://www.cosapi.com.pe/Site/Index.aspx?aID=1407#:~:text=mercado%20que%20permite%20la%20detecci%C3%B3n,colaboradores%2C%20incluyendo%20fuentes%20de%20financiamiento]

- #strong("Eficiencia de procesos logísticos internos: ") Aplica ingeniería de valor y planificación colaborativa para optimizar costos y tiempos. Por ejemplo, en la construcción de un templo en Lima logró reducir la obra de 14 a 11.5 meses gracias a una fase de preconstrucción optimizada@fn8. A partir de esta metodología de mejora continua y coordinación anticipada, trae un desarrollo de proyecto de calidad. Un ejemplo de ello, es que Cosapi obtuvo un 98% en la evaluación de abastecimiento responsable realizada por Anglo American (proyecto Quellaveco)@fn8, indicando altos estándares en sus procesos de compra y control logístico.

- #strong("Cadena de suministro nacional robusta: ") La compañía invierte fuertemente en proveedores locales. En 2023 todo el grupo Cosapi destinó S/160 millones a compras a proveedores nacionales (22% de ellas en provincias)@fn8, lo que garantiza disponibilidad continua de insumos y apoya el contenido local exigido en las obras. Además, mantiene esquemas de contratos a largo plazo y pagos puntuales, afianzando la lealtad de sus proveedores estratégicos. Estos compromisos internos favorecen una logística de abastecimiento ágil y confiable.

#strong(text(15.5pt, "Oportunidades"))\

El crecimiento de proyectos APP, la reactivación de inversiones públicas y privadas, así como el impulso de criterios ESG, configuran un pipeline de obra creciente. Tales condiciones permiten a Cosapi Concesiones diversificar su portafolio, fortalecer alianzas público-privadas y explorar nuevas sinergias sectoriales. Desarrollando estos puntos:

- #strong("Cartera PPP en expansión: ") El entorno de inversión pública-pero-privada en Perú presenta un fuerte dinamismo. En 2024 ProInversión adjudicó 16 proyectos APP por USD 8,956 millones (récord de la década)#footnote[ProInversion https://www.investinperu.pe, Agencia de Promocion de la Inversion Privada. (s. f.). BALANCE 2024: PROINVERSIÓN MARCA RÉCORD AL ADJUDICAR 16 PROYECTOS POR CERCA DE USD 9000 MILLONES. © Proinversion. https://www.investinperu.pe/es/pi/detail-news/balance-2024-proinversion-marca-record-al-adjudic#:~:text=Lima%2C%2031%20de%20diciembre%20de,de%2010%20millones%20de%20habitantes]<fn9>. Asimismo, Cosapi Concesiones evalúa una cartera de más de USD 10,000 millones en proyectos de concesión. Se prevé que esta tendencia continúe: ProInversión reporta unos USD 10.4 mil millones en proyectos APP a licitar en 2024-25@fn9. Este pipeline de grandes obras de transporte, agua e infraestructura (nuevos tramos de carreteras, extensión del Metro de Lima, ampliación del aeropuerto, etc.) eleva la demanda de suministros y brinda a Cosapi oportunidades para ampliar su volumen de aprovisionamiento. Además, el crecimiento económico proyectado (3.2% en 2024 y 3.4% en 2025@fn8) y la reactivación de la inversión pública y privada apoyan una mayor ejecución de proyectos, lo que puede mejorar los plazos de compra y negociación logística.

- #strong("Impulso a la innovación y sostenibilidad: ") Las tendencias globales favorecen a empresas con prácticas de logística avanzada. Cosapi ya implementa tecnologías para la gestión de riesgos (por ejemplo, uso de códigos QR para identificación de peligros)@fn8, lo que puede extenderse al seguimiento de insumos en obra. Además, ha obtenido certificaciones relevantes (ISO 37301 de cumplimiento normativo) y reconocimientos ambientales (Certificación “Huella de Carbono Perú” nivel 1 por calcular sus emisiones GEI). Esta gestión sostenible le permite aprovechar oportunidades en proyectos que exijan criterios ESG altos y podrían abrir mercado en iniciativas verdes y tecnológicas.

- #strong("Sinergias en sectores demandantes: ") El repunte de la minería (por ejemplo, la entrada en operación de Quellaveco impulsó un crecimiento minero de 8.9% en 2023@fn8) y el desarrollo agroexportador (Majes-Siguas) crean demanda de infraestructura complementaria. Como parte del consorcio de Majes-Siguas II, Cosapi participa en el desarrollo de canales y túneles de riego#footnote[COSAPI: Proyecto Majes-Siguas empieza en junio. (s. f.). https://www.cosapi.com.pe/Site/Index.aspx?aID=1522#:~:text=Este%20nuevo%20acuerdo%20establece%20una,38%2C500%20hect%C3%A1reas%20de%20tierras%20eriazas], lo cual expande su experiencia en proyectos hídricos y viales. El énfasis en obras hídricas y redes viales también favorece la logística de aprovisionamiento al mejorar la conectividad (nuevas vías y accesos reducen tiempos de transporte de materiales).

#strong(text(15.5pt, "Debilidades"))\

La dependencia de recursos humanos y logísticos de otras unidades, así como una cartera de proyectos reducida, pueden afectar su agilidad y la capacidad de negociación. Estas restricciones internas requieren atención para robustecer estructuras y diversificar riesgos. Desarrollando estos puntos:

- #strong("Estructura interna limitada: ") La unidad de Concesiones es relativamente pequeña: a fines de 2023 no tenía empleados propios registrados (0 colaboradores)@fn8. Esto indica que depende directamente del personal de otras filiales de Cosapi para gestionar compras y logística, lo que puede generar demoras o falta de foco en las tareas de aprovisionamiento. La ausencia de equipo propio de adquisiciones y logística en Concesiones reduce la agilidad operativa y dificulta ampliar capacidad rápidamente.

- #strong("Concentración en pocos proyectos: ") Actualmente Cosapi Concesiones administra solo dos proyectos concesionados relevantes (Línea 2 del Metro de Lima y Majes-Siguas II)​@fn8. Esta baja diversificación implica que su cadena de suministro depende en gran medida de estos contratos; cualquier retraso, cambio de alcance o contingencia en uno de ellos impacta directamente en el volumen de compra y en la planificación logística general. Además, al concentrar recursos en pocas obras, pierde economías de escala que obtendría participando simultáneamente en múltiples proyectos de diferentes tipos.

#strong(text(15.5pt, "Amenazas"))\

El entorno macro y micro sectoresamenazan la ejecución oportuna y rentable de proyectos de concesión. La contracción económica, la volatilidad política, los fenómenos climáticos y las tensiones en la cadena de suministro global incrementan la incertidumbre. Dichos factores pueden derivar en sobrecostos, retrasos y la necesidad de renegociar términos contractuales, impactando la rentabilidad y la continuidad de las operaciones de Cosapi Concesiones. Desarrollando estos puntos:

- #strong("Contracción del sector construcción: ") El entorno macroeconómico ha sido adverso. En 2023 la actividad económica de Perú se contrajo 0.7% y la construcción en particular cayó 9.2% en el tercer trimestre (caída récord en 12 años)@fn8. Esta caída se traduce en una menor ejecución de obras privadas y públicas, lo que puede reducir la oferta y volumen de materiales disponibles en el mercado. Un mercado contraído presiona los márgenes de negociación con proveedores y puede causar sobreoferta de insumos (bajando precios, como se observó con un −0.2% en los precios de materiales en el segundo semestre de 2023​@fn8) o, por el contrario, generación de stocks ociosos.

- #strong("Factores externos e incertidumbre: ") La logística de aprovisionamiento está expuesta a riesgos externos. El fenómeno climático El Niño (2024–2025) es impredecible y puede afectar rutas de acceso a obras o disponibilidad de materiales @fn8. A esto se suman los vaivenes políticos y económicos propios de Perú (elecciones, cambios de normativa), además de posibles interrupciones globales en la cadena de suministro (pandemia residual, tensiones comerciales) y la competencia de consorcios multinacionales. Estos factores podrían encarecer fletes, generar retrasos en importaciones o imponer nuevas regulaciones, impactando negativamente los tiempos y costos del aprovisionamiento.

== Macro Entorno
El análisis del macro entorno permite identificar las variables externas que impactan la cadena de suministro y la ejecución de proyectos de concesión. A través de un examen de los factores socioculturales, económicos, políticos, tecnológicos, ecológicos y legales, se podrá entender mejor el contexto en el que operan Cosapi Concesiones.
#pagebreak()
#strong(text(15.5pt, "Sociocultural"))\

Perú tiene una población de 34,39 millones (2024) con edad promedio creciente (33,8 años)#footnote[Ec, R. (2024, 12 julio). Perú registra 34 millones de habitantes al 2024, según el INEI. El Comercio Perú. https://elcomercio.pe/lima/sucesos/peru-la-poblacion-alcanza-los-34-millones-de-habitantes-segun-el-inei-instituto-nacional-de-estadistica-e-informatica-ultimas-noticia/#:~:text=Edad%20promedio%20de%20la%20poblaci%C3%B3n,se%20ubica%20en%2033%2C8%20a%C3%B1os]. Hay alta diversidad étnica (27% se autoidentifica indígena) y fuertes tradiciones regionales. Esto implica, por ejemplo, que los proyectos de infraestructura deben considerar prácticas culturales locales y necesidades de comunidades diversas. El mercado laboral también presenta retos: el empleo juvenil y la informalidad son altos (la tasa de subempleo fue $~$45,4% entre abril 2023 y marzo 2024) y persiste un amplio sector de obreros sin certificación formal. En respuesta, COSAPI ha promovido la capacitación profesional: en 2023 fue acreditada por el MTPE como entidad certificadora de competencias laborales#footnote[COSAPI: COSAPI ES ACREDITADA COMO ENTIDAD CERTIFICADORA DE COMPETENCIAS CON VALOR OFICIAL EN PERÚ. (s. f.). https://www.cosapi.com.pe/Site/Index.aspx?aID=2618#:~:text=Cosapi%2C%20empresa%20l%C3%ADder%20en%20el,calidad%20en%20un%20perfil%20laboral], lo que eleva la calificación de su mano de obra. Asimismo, la empresa fomenta la inclusión de género (p. ej. asociándose con Women in Mining para impulsar el desarrollo de mujeres en construcción). Estos factores condicionan la disponibilidad y perfil de los trabajadores en la cadena logística.

#strong(text(15.5pt, "Económico"))\

En los últimos 2–3 años la economía peruana ha sido volátil y condiciona la cadena de suministros de construcción. El sector construcción creció 4,3% en el segundo trimestre de 2023 por obras estatales (protección contra inundaciones en Casma, Huarmey, etc.), pero acumuló una contracción de –9,2% entre enero–octubre 2023. El PIB nacional rondó el 1% de variación en 2023, con proyecciones de recuperación moderada (≈3.2–3.4% en 2024–25) impulsada por la minería e infraestructura. La inflación de insumos, en particular, se moderó: el Índice de Precios de Materiales de Construcción a nivel nacional cayó 1,39% en 2023, reflejando abaratamiento de algunos insumos metálicos y cerámicos. Sin embargo, la incertidumbre macro (tipo de cambio e intereses relativamente altos) encarece el financiamiento y la importación de materiales.

La cartera de proyectos de COSAPI refleja estas tendencias: según su informe 2023, más de la mitad de sus obras vigentes son viales (51%) y de edificación (32%), alineándose con la inversión pública en infraestructura. Además, COSAPI Concesiones participa en PPP de gran escala (línea 2 del Metro de Lima, USD 5.490 millones; proyecto Majes Siguas, USD 405 millones). De cara al futuro, el gobierno ha anunciado una cartera PPP superior a USD 10 mil millones, apuntalando la demanda de materiales. 

#strong(text(15.5pt, "Político"))\

La estabilidad y las políticas públicas impactan fuertemente el aprovisionamiento. En el último bienio Perú vivió cambios políticos bruscos: desde la vacancia de 2022, protestas sociales y gobiernos interinos hasta las elecciones de 2024. Esto generó cierta incertidumbre en la ejecución de proyectos, retrasos en concesiones y tensiones con comunidades. Sin embargo, el Estado ha mantenido el impulso a la infraestructura. Por ejemplo, el Ministerio de Transportes está ejecutando varios proyectos viales concesionados clave, como el Evitamiento Chancay-Chancayllo (USD 120 M) y el Par Vial Pasamayo (USD 175 M), para mejorar la conectividad hacia puertos. También se promueve logística portuaria: el antepuerto del Callao (S/163.5 M) sacará carga fuera de los concesionarios actuales, y se trabaja en una hoja de ruta para digitalizar el cabotaje marítimo (Ley N°32049, 2022).

En el ámbito normativo, se han publicado diversas leyes y decretos para facilitar la inversión pública. Recientemente el gobierno aprobó medidas en contrataciones públicas (Decreto Legislativo N°1553, mayo 2023) y reformó la Ley PPP (DL 1362) con DL 1691 (octubre 2024)#footnote[Decreto legislativo n°1553. (s. f.). https://www.mef.gob.pe/es/?option=com_docman&language=es-ES&Itemid=101119&lang=es-ES&view=list&slug=decreto-legislativo-1]<fn10>, buscando agilizar obras e inversiones. Asimismo, se ajustaron esquemas de Obras por Impuestos (DS 011-2024-EF) para ampliar beneficios tributarios a las empresas privadas#footnote[Garrigues. (2024, 14 febrero). Perú: Se modifican disposiciones que regulan la modalidad de Obras por Impuestos. Garrigues. https://www.garrigues.com/es_ES/noticia/peru-modifican-disposiciones-regulan-modalidad-obras-impuestos#:~:text=,Impuesto%20a%20la%20Renta%20correspondiente]. Para COSAPI, experto en concesiones, estos cambios se traducen en oportunidades (mayor impulso a PPP) pero también en nuevos requisitos (p. ej. negociación previa obligatoria antes de arbitraje en OxI). La supervisión de proyectos concesionados la ejerce OSITRAN y PROINVERSIÓN, lo cual brinda marco institucional que protege a los inversores.

#strong(text(15.5pt, "Tecnológico"))\

La transformación digital y la innovación tecnológica están revolucionando la logística en construcción. A nivel global, tecnologías como BIM (Modelado de Información de Construcción), IoT, drones y análisis de datos optimizan la cadena de suministro. En Perú, aunque la construcción tradicionalmente adopta poco TIC, la pandemia aceleró cambios: ya se reporta que más del 20% de maestros de obra buscan cotizaciones de materiales en línea, señal de que crece la cultura digital. COSAPI ha incorporado herramientas avanzadas en sus proyectos: por ejemplo, en la edificación del hospital de Huarmey implementó la metodología VDC (Virtual Design & Construction), que integra diseño BIM con gestión de ejecución. También migró su centro de datos a la nube, instaló sistemas de seguridad informática y de gestión de inventarios digitales para el aprovisionamiento.

Otras tecnologías emergentes relevantes son: raspado de datos y AI para prever demanda de insumos; blockchain para trazabilidad en compras internacionales; equipos automatizados (grúas robotizadas, impresión 3D de componentes) y sensores IoT que monitorean el estado de máquinas y rutas logísticas. Además, plataformas especializadas (p. ej., soluciones SaaS de compras) están mejorando la eficiencia: según Equip Construye, un 80% de las empresas aún gestiona cotizaciones manualmente, por lo que la digitalización ofrece gran potencial de ahorro. En conjunto, estas innovaciones tecnológicas reducen tiempos de entrega, optimizan rutas y minimizan errores en la cadena de suministro de materiales. COSAPI Concesiones, al aliarse con expertos internacionales (consorcios globales del metro), adquiere acceso a estas prácticas avanzadas, lo que mejora la competitividad de su logística de aprovisionamiento.

#strong(text(15.5pt, "Ecológico"))\

Las normas ambientales y la sostenibilidad son cada vez más relevantes. El Estado ha endurecido los requisitos de evaluación de impacto: el SENACE aprobó cientos de proyectos (transporte, saneamiento, residuos) en 2024 con estándares ambientales estrictos. COSAPI misma tiene certificación ISO 14001@fn8 y fue reconocida por el Ministerio del Ambiente por medir su “Huella de Carbono” (nivel 1), lo cual muestra un compromiso corporativo. En la etapa de aprovisionamiento logístico, esto implica cumplir con regulaciones de manejo de desechos (PAMA para obras grandes), limitar emisiones en transporte y priorizar materiales sostenibles. Por ejemplo, la reciente actualización de normas ambientales para proyectos de residuos sólidos (RM 260-2023) exige planes de gestión de desechos, aplicables a las obras de infraestructura.

Por otro lado, el cambio climático es un factor crítico: el Fenómeno El Niño extremo podría provocar inundaciones y deslizamientos que dañen carreteras y entorpezcan cadenas de suministros. Por ello, las obras viales actuales incorporan diseños resilientes y sistemas de drenaje mejorado. Además, hay iniciativas para descarbonizar la cadena logística: se estudia el uso de combustibles menos contaminantes y la digitalización del cabotaje (Ley 32049/2022), lo cual podría desplazar parte de la carga de camión a barco, reduciendo huella. COSAPI incluye criterios de sostenibilidad en sus contratistas (política de recompra de equipos electrónicos, limpieza de CO2), lo cual, hace que las exigencias ecológicas incrementan la complejidad logística (mayores trámites y prácticas más limpias), pero también abren oportunidades de innovación en la cadena de suministro verde.

#strong(text(15.5pt, "Legal"))\

El marco legal que rige la construcción e importación de insumos es dinámico. En los últimos años se han promulgado normas relevantes: en mayo 2023 el Decreto Legislativo N°1553 introdujo medidas para reactivar inversiones públicas y simplificar contrataciones@fn10. En octubre 2024 el DL N°1691 modificó el DL1362 (Ley PPP) y el DL1543 para mejorar la promoción de APP, lo que favorecería la adjudicación de proyectos en los que participa COSAPI Concesiones. En paralelo, la Ley de Obras por Impuestos fue reformada (DS 011-2024-EF), ampliando la negociabilidad de certificados de inversión (CIP) y obligando la negociación previa en controversias. Estas modificaciones legales permiten mayor flexibilidad financiera a las empresas y plazos contractuales más claros.

En el ámbito laboral y tributario también hay cambios: se mantienen regulaciones estrictas de seguridad laboral (COSAPI cumple ISO 45001) y de contratación (limitaciones a la tercerización, pago puntual de beneficios). En lo comercial, los insumos importados están sujetos a aranceles y requisitos fitosanitarios vigentes; por ejemplo, en 2023 el gobierno priorizó la producción nacional de tubos de PVC para saneamiento (dejando en evidencia una protección de proveedores locales). Además, acuerdos comerciales (como el TLC con China y otros) influyen en costos de insumos. COSAPI, con un riguroso sistema de compliance (certificaciones ISO 37001 antisoborno, ISO 37301 compliance), debe velar por el cumplimiento de normas anticorrupción y anticontaminación en cada contrato.

== Entorno Estratégico
COSAPI Concesiones participa en grandes proyectos de infraestructura bajo esquemas de Asociaciones Público-Privadas (APP) en Perú, como la Línea 2 del Metro de Lima (inversión $~$USD 5.490 millones) y el proyecto Majes Siguas ($~$USD 405 millones). En estos megaproyectos, la etapa de aprovisionamiento logístico –compra de insumos, equipos y materiales– está influida por factores estratégicos del mercado.

#strong(text(15.5pt, "Poder de negociación de los proveedores - Alto"))\

En el mercado de concesiones, el poder de los proveedores es elevado debido a la escasez de fabricantes especializados y al alto grado de concentración en insumos críticos. Los proveedores de cemento, acero, maquinaria pesada y sistemas electromecánicos cuentan con tecnología punta y pocos competidores globales, lo que les otorga amplia capacidad para fijar precios, plazos de entrega y condiciones de servicio. Esta situación obliga a COSAPI a diseñar estrategias de negociación de gran envergadura y a buscar alternativas de diversificación para no depender de un número reducido de actores.

- #strong(text("Insumos especializados y pocas alternativas: ")) Los proveedores clave (cemento, acero, maquinaria pesada, equipos ferroviarios) son escasos y globales. Por ejemplo, en la Línea 2 del Metro de Lima el concesionario debe proveer trenes y sistemas electromecánicos específicos@fn8, cuyos fabricantes globales (p. ej. Alstom, Siemens, CCCC) tienen alto poder.

- #strong(text("Estrategias de COSAPI: ")) La compañía mitiga este poder negociando en volumen y buscando alianzas. En 2023 COSAPI obtuvo “convenios con principales marcas” y descuentos considerables en licitaciones transversales, además de tercerizar almacenes para reducir costos logísticos@fn8. Asimismo, promueve que sus proveedores se vean como “socios estratégicos” para crecimiento mutuo y calidad de obra.

- #strong(text("Compra local y diversificación: ")) Se impulsa la participación de proveedores nacionales y regionales. En 2023 COSAPI destinó S/160 millones a compras con proveedores peruanos, de los cuales 22 % correspondieron a empresas provinciales@fn8. Esta diversificación reduce la dependencia de proveedores externos únicos, equilibrando el poder de negociación.

#strong(text(15.5pt, "Poder de negociación de los clientes - Alto"))\

Los “clientes” en este caso son entidades estatales que licitan y supervisan las APP, como PROINVERSIÓN o el Ministerio de Transportes. Al manejar presupuestos multimillonarios y criterios técnicos muy estrictos, ejercen una fuerte presión sobre plazos, estándares de calidad y condiciones financieras. Su capacidad de revisar múltiples ofertas y de imponer cláusulas de servicio a largo plazo limita la flexibilidad de COSAPI en la negociación de precios y cronogramas.

- #strong(text("Insumos especializados y pocas alternativas: ")) Al ser proyectos APP, el “cliente” es el Estado (a través de PROINVERSION/MTC u otras entidades públicas)#footnote[COSAPI concesiones. (s. f.-b). https://www.cosapi.com.pe/Site/Index.aspx?aID=1407#:~:text=Adem%C3%A1s%2C%20COSAPI%20forma%20parte%20de,inversi%C3%B3n%20total%20de%20US%24405%20millones]. Estas entidades definen contratos con plazos largos, estándares técnicos y condiciones financieras estrictas, ejerciendo un fuerte poder de negociación.

- #strong(text("Términos contractuales rígidos: ")) Los contratos PPP imponen obligaciones de servicio a largo plazo. Por ejemplo, en la licitación de la Carretera Longitudinal de la Sierra (Tramo 4), la concesión se pactó por 25 años bajo modalidad APP cofinanciada#footnote[ProInversion https://www.investinperu.pe, Agencia de Promocion de la Inversion Privada. (s. f.-b). PROINVERSIÓN: SIETE POSTORES COMPITEN POR LA LONGITUDINAL DE LA SIERRA TRAMO 4. © Proinversion. https://www.investinperu.pe/es/pi/detail-news/proinversion-siete-postores-compiten-por-la-longi#:~:text=El%20plazo%20de%20concesi%C3%B3n%20ser%C3%A1,durante%20el%20periodo%20de%20concesi%C3%B3n]<fn11>, garantizando estándares de calidad. Esto refleja cómo el Estado fija reglas operativas y tarifarias que deben cumplir los concesionarios, limitando la flexibilidad negociadora de COSAPI.

- #strong("Competencia en licitaciones: ") En la etapa de adjudicación, el Estado compara múltiples ofertas. La existencia de varios consorcios interesados () también refuerza el poder del cliente: puede escoger la oferta más ventajosa en términos de precio, plazo o alcance, presionando a COSAPI a presentar propuestas muy competitivas.

#strong(text(15.5pt, "Amenaza de nuevos entrantes - Media"))\

Si bien el mercado de concesiones APP es atractivo, las barreras de entrada son significativas. Los altos requisitos de capital, la necesidad de experiencia técnica probada y el cumplimiento de estrictos estándares de garantía financiera y desempeño filtran a los participantes. No obstante, el creciente pipeline de proyectos PPP despierta el interés de nuevos grupos inversores, situando la amenaza en un nivel medio.

- #strong(text("Altas barreras de capital y experiencia: ")) Los proyectos concesionados demandan enormes inversiones y conocimientos técnicos. Por ejemplo, solo la Línea 2 del Metro involucra $~$USD 5.490M. Estas magnitudes requieren consorcios consolidados con respaldo financiero y experiencia previa, lo que dificulta el ingreso de nuevos competidores sin historial probado.

- #strong(text("Portafolio amplio pero competitivo: ")) El gobierno peruano promueve un gran portafolio PPP (aprox. USD70.000 millones en proyectos anunciados), atrayendo interés de inversores. Sin embargo, aunque hay oportunidades en número, el nivel de requisitos (garantías, financiamiento, capital local, etc.) filtra a los candidatos. Solo empresas consolidadas suelen cumplir estos criterios, por lo que la amenaza de nuevos entrantes significativos en el nicho de concesiones de gran escala es baja a mediana.

- #strong(text("Preferencia por consorcios establecidos: ")) Dada la complejidad legal y financiera, el Estado suele favorecer licitaciones con consorcios que demuestren experiencia en PPP similares. COSAPI Concesiones participa activamente en nuevos procesos (ha reportado evaluación de proyectos por >USD 10.000M), pero enfrenta como rival a grandes jugadores nacionales e internacionales (organizaciones Chilenas y Brasileñas), limitando la llegada de “recién llegados”.

#strong(text(15.5pt, "Amenaza de productos sustitutos - Baja"))\

En infraestructuras de transporte, agua o energía, no existen sustitutos directos que reemplacen la construcción física de carreteras, metros o plantas de tratamiento. La alternativa sería cambiar la modalidad de gestión (APP versus obra pública directa), pero no la infraestructura misma. Por lo tanto, la amenaza de sustitutos en la fase logística de aprovisionamiento es mínima.

- #strong(text("Infraestructura física irremplazable: ")) Los proyectos de infraestructura (metros, carreteras, hospitales) no tienen sustitutos directos. No hay tecnología o servicio alternativo que reemplace la construcción física de una red ferroviaria o carretera. Por ejemplo, el Metro de Lima implica 34 km de túneles y flota de trenes eléctricos@fn8; cambiarlo por otro medio (autobuses o teleférico) no ofrece la misma capacidad ni alcance.

- #strong(text("Cambio en modelo de provisión: ")) A nivel más estratégico, un “sustituto” sería que el Estado ejecute proyectos sin concesión (obra pública directa en lugar de APP). Sin embargo, esto no sustituye la infraestructura misma, sino sólo la modalidad de gestión. En el mercado actual, la modalidad APP sigue siendo la vía preferida para financiar e implementar grandes obras, por lo que la amenaza de sustituir los proyectos en sí (o la etapa de aprovisionamiento logístico) por soluciones alternativas es muy baja.

- #strong(text("Escalabilidad: ")) Cualquier alternativa (p. ej., adquirir equipos usados en lugar de nuevos, o materiales alternativos) no cumple los requerimientos de durabilidad, estándares o volumen de las obras concesionadas.

#strong(text(15.5pt, "Rivalidad entre competidores existentes - Alta"))\

La competencia en el segmento de concesiones APP es intensa. Diversos consorcios locales e internacionales pujan por cada proyecto, ajustando márgenes y plazos para ganar licitaciones. La disponibilidad limitada de las grandes obras y la repetición de procesos de licitación elevan la rivalidad a un nivel alto.

#pagebreak()
- #strong(text("Consorcios PPP muy competitivos: ")) La licitación de concesiones atrae a múltiples grandes jugadores. Por ejemplo, para la Carretera Longitudinal de la Sierra Tramo 4 (USD 1.200M) PROINVERSIÓN precalificó siete consorcios internacionales@fn11 (incluyendo firmas de España, China, y conglomerados latinoamericanos). Esto muestra la alta rivalidad: varias empresas de ingeniería se disputan cada proyecto.

- #strong(text("Alta frecuencia de competencia: ")) Cada nuevo proceso APP suele tener de 3 a 7 o más postores. Por ejemplo, en otros concursos recientes de PROINVERSIÓN compitieron tres consorcios por una planta de tratamiento de aguas (PTAR) en Puerto Maldonado#footnote[MEF. (s. f.). Tres postores compiten para construir y operar PTAR Puerto Maldonado. En gop.pe. https://www.gob.pe/es/n/925293]. Esto obliga a COSAPI a ofertar con márgenes ajustados de precio, plazo y calidad para ganar la adjudicación.

- #strong(text("Competidores locales e internacionales: ")) Además de los consorcios globales (Sacyr, CCCC, etc. citados en ProInversion@fn11), en el ámbito local existen empresas con capacidad (Graña y Montero, Mota-Engil, OHL, entre otras) que también compiten en las concesiones. La rivalidad se intensifica cuando el número de proyectos PPP es limitado y se concentran grandes inversiones: obliga a COSAPI Concesiones a diferenciarse por eficiencia logística, innovación y solidez financiera.

//== Matrización


#pagebreak()