= Justificación

La mejora del proceso logístico de aprovisionamiento es fundamental para garantizar el correcto funcionamiento de las operaciones de COSAPI Concesiones#footnote[Logística de aprovisionamiento: qué es, importancia y tipos. (s. f.). https://blog.toyota-forklifts.es/logistica-aprovisionamiento-que-importancia-tipos#:~:text=El%20aprovisionamiento%20desempe%C3%B1a%20un%20papel,Una]. Según la literatura especializada, un aprovisionamiento eficiente permite mayor previsibilidad en los tiempos de entrega y mejora el rendimiento operativo. Al optimizar este proceso se reducen las interrupciones por falta de materiales, asegurando así la continuidad de la cadena de suministro y la productividad de las obras.

== Beneficiarios Directos
Los beneficiarios directos son aquellos grupos que participan directamente en las operaciones del proyecto y reciben beneficios inmediatos de su ejecución. En el caso de la mejora del aprovisionamiento en COSAPI Concesiones, se identifican los siguientes beneficiarios directos:

- #strong("Personal del área de aprovisionamiento y almacén: ") Este equipo de compras y logística emplea directamente los procesos y herramientas del proyecto#footnote[Mecalux. (s. f.-c). Logística de aprovisionamiento, clave en la cadena de suministro. https://www.mecalux.com.mx/blog/logistica-de-aprovisionamiento#:~:text=Otro%20de%20los%20grandes%20beneficios,sin%20sufrir%20roturas%20de%20stock]<fn15>. Con la implementación de sistemas de seguimiento y planificación más eficientes, se reducen tareas manuales y errores en el registro de pedidos. En la práctica, esto garantiza que siempre se disponga de los materiales necesarios sin interrupciones de stock, lo que evita demoras en la reposición y mantiene niveles adecuados de insumos para la producción diaria.

- #strong("Equipos operativos y de proyecto (ingenieros, supervisores de obra, etc.): ") Son usuarios finales del resultado del proceso logístico. Una logística optimizada incrementa la puntualidad y rendimiento de las operaciones@fn15. Estos profesionales se beneficiarán de entregas de insumos más predecibles y puntuales, lo que evita paradas imprevistas en la obra. Como resultado, experimentan mayor eficiencia en el avance de sus actividades diarias y mejor cumplimiento de los cronogramas de construcción.

- #strong("Proveedores de materiales y servicios: ") Aunque externos, estos actores interactúan directamente con el proceso de aprovisionamiento del proyecto. La mejora logística establece entregas periódicas y coordinadas, de modo que los proveedores pueden planificar mejor sus despachos@fn15. Esto genera un suministro estable y de calidad, beneficioso para ambas partes: los proveedores obtienen relaciones comerciales predecibles, mientras que COSAPI recibe insumos a tiempo y en condiciones consistentes.

== Beneficiarios Indirectos
Los beneficiarios indirectos son aquellos que no participan directamente en el proyecto pero obtienen mejoras en su entorno gracias a él. En este proyecto de mejora logística, se identifican los siguientes beneficiarios indirectos:

- #strong("Gerencia y equipos de planificación interna de COSAPI Concesiones: ") Aunque no intervienen en las operaciones diarias, estos gestores se benefician de la implementación de indicadores y reportes más precisos sobre el flujo de materiales. Disponer de información confiable (como niveles de inventario en tiempo real y demanda proyectada) facilita la toma de decisiones estratégicas y la asignación de recursos. En consecuencia, la gerencia afronta menos contingencias operativas y puede enfocar sus esfuerzos en optimizar otros aspectos del negocio.

- #strong("Clientes externos y usuarios finales de las concesiones (entidades estatales, comunidad usuaria de la infraestructura, etc.):") Estos actores no forman parte del proceso logístico, pero se benefician indirectamente de sus mejoras. Una cadena de suministro más eficiente redunda en la entrega puntual de proyectos de infraestructura. De hecho, se ha observado que un aprovisionamiento optimizado mejora el servicio final al cliente@fn15. En este contexto, los organismos contratantes y usuarios de las obras verán cumplidos los plazos de entrega con mayor fiabilidad, lo que se traduce en mayor satisfacción y confianza en los proyectos de COSAPI Concesiones.

- #strong("Comunidad local y demás grupos de interés: ") Al asegurarse el abastecimiento oportuno de materiales, las obras concesionadas avanzan sin interrupciones indebidamente largas. Esto beneficia indirectamente a la población servida por la infraestructura. En proyectos análogos se contempla como beneficiarios indirectos «a todos los habitantes de las comunidades ubicadas en un área cercana» a la obra@fn15. De igual modo, al reducir retrasos en la construcción, la comunidad disfruta antes de los servicios e instalaciones previstas (por ejemplo, vías de transporte o plantas de servicios), mejorando su calidad de vida de forma indirecta.
#pagebreak()