= Objetivos

== Objetivo General
Con base en el diagnóstico anterior y en la literatura sobre gestión de la cadena de suministro, se formula el siguiente objetivo general:

"Diseñar e implementar un modelo integrado de gestión de aprovisionamiento de materiales que garantice la disponibilidad oportuna de insumos, optimice los costos logísticos y refuerce la resiliencia de la cadena de suministro ante disrupciones, contribuyendo así al éxito de los proyectos concesionados."

Con este objetivo se pretende equilibrar la eficiencia operativa con la capacidad de respuesta frente a riesgos externos, en línea con recomendaciones que enfatizan la creación de cadenas más resilientes#footnote[Hardin, K., Laaper, S., Parrott, A., & Gold, S. (2024, 3 septiembre). Meeting the challenge of supply chain disruption. Deloitte Insights. https://www2.deloitte.com/us/en/insights/industry/manufacturing/realigning-global-supply-chain-management-networks.html]. Además, se alinea con la estrategia nacional de infraestructura, buscando soportar las inversiones previstas en el PNIC mediante un aprovisionamiento estratégico y fiable#footnote[Peru - Infrastructure development. (2023, 30 diciembre). International Trade Administration | Trade.gov. https://www.trade.gov/country-commercial-guides/peru-infrastructure-development#:~:text=In%202019%2C%20Peru%20launched%20its,they%20include%20clearing%20the%20Amazon]. La consecución de este objetivo facilitará el desarrollo de las obras planificadas, minimizando retrasos y sobrecostos en la etapa de aprovisionamiento y generación de valor para COSAPI Concesiones.

== Objetivos Específicos
1. #strong("Mejorar la planificación de compras y demanda: ") A partir del análisis se busca que COSAPI Concesiones pueda implementar un sistema integrado de planificación de la demanda y compras, apoyado en técnicas de previsión y MRP, con el fin de incrementar la precisión de los pronósticos de requerimientos de materiales en al menos un 15% para el cierre de 2025. De este modo se garantizará la disponibilidad oportuna de insumos en obra, ajustando el volumen de adquisiciones a la demanda real y evitando tanto desabastecimientos como excedentes innecesarios.#footnote[Ibm. (2023, 13 junio). ¿Qué es la planificación de la demanda? IBM. https://www.ibm.com/mx-es/topics/demand-planning#:~:text=La%20planificaci%C3%B3n%20de%20la%20demanda,preparados%20para%20la%20pr%C3%B3xima%20venta]<fn13>

2. #strong("Optimizar el control de inventarios: ") A partir del análisis se busca que COSAPI Concesiones optimice el control de inventarios mediante la implementación de un sistema de gestión de almacenes (SGA) en tiempo real y técnicas de clasificación ABC, reduciendo la permanencia de materiales obsoletos y elevando la rotación de stock. El objetivo es disminuir en al menos un 20% los costos asociados al mantenimiento de inventarios para el cierre de 2025, asegurando niveles de inventario óptimos (ni faltantes ni excesivos) conforme a la demanda de obrainnecesarios.@fn13

3. #strong("Mejorar la coordinación logística y de entregas en obra: ") A partir del análisis se busca que COSAPI Concesiones mejorará la coordinación entre el cronograma de construcción y las fechas de suministro de materiales para incrementar la puntualidad de las entregas en al menos un 95% para mediados de 2026. Para ello se sincronizarán los datos de inventarios y órdenes de compra con los hitos de ingeniería, garantizando rapidez en las entregas y calidad de la información entre almacenes, proveedores y frentes de obra#footnote[Mecalux. (s. f.-b). 10 objetivos de la logística y cómo alcanzarlos. https://www.mecalux.es/blog/objetivos-de-la-logistica#:~:text=El%20primer%20objetivo%20de%20la,las%20propuestas%20de%20valor%20que]

4. #strong("Integrar tecnología en el aprovisionamiento: ") A partir del análisis se busca que COSAPI Concesiones integre soluciones tecnológicas (un ERP unificado, sistemas IoT de seguimiento y plataformas digitales) en su cadena de suministro para centralizar la información en una sola plataforma. El objetivo es que para fines de 2025 toda la información relevante (órdenes de compra, inventarios y flujos logísticos) esté disponible en tiempo real, optimizando la visibilidad de la cadena de suministro y mejorando la toma de decisiones ante cambios#footnote[¿Qué es MRP? La clave de una fabricación eficiente | SAP. (s. f.). SAP. https://www.sap.com/latinamerica/products/erp/what-is-mrp.html#:~:text=Actualmente%2C%20los%20sistemas%20de%20ERP,la%20eficiencia%20de%20la%20producci%C3%B3n]<fn14>

5. #strong("Fortalecer la relación y desempeño de proveedores: ") A partir del análisis se busca que OSAPI Concesiones desarrolle un programa de gestión de proveedores enfocado en la evaluación de desempeño y colaboración. Se planteará mejorar en al menos un 20% la calificación promedio de desempeño (cumplimiento de plazos de entrega y calidad de materiales) de los proveedores críticos para mediados de 2026. Para ello se establecerán métricas claras de evaluación y se promoverá la comunicación continua (revisiones periódicas, auditorías y capacitaciones conjuntas), garantizando así una red de suministro colaborativa y confiable.

6. #strong("Gestionar los riesgos logísticos: ") A partir del análisis se busca que COSAPI Concesiones implemente un sistema de gestión de riesgos que identifique y mitigue las principales amenazas al abastecimiento (retrasos imprevistos, variaciones de precios, eventos externos). El objetivo es reducir en al menos un 30% la incidencia de interrupciones imprevistas en el aprovisionamiento para finales de 2025@fn14. Para ello se elaborarán planes de contingencia con proveedores alternativos y se realizará monitoreo continuo de factores de riesgo, fortaleciendo la continuidad de los proyectos ante eventualidades externas.

7. #strong("Mejorar la comunicación e integración interdepartamental: ") A partir del análisis se busca que COSAPI Concesiones establezca mecanismos formales de comunicación entre logística, ingeniería y contratistas, mediante reuniones periódicas y reportes compartidos. El objetivo es reducir en un 50% los errores y duplicidades en la gestión de materiales para finales de 2025, garantizando que todas las áreas dispongan de información actualizada y coherente sobre necesidades y avances de obra#footnote[Obdulio-Sim. (2024, 26 septiembre). Cómo establecer objetivos SMART en logística - Grupo SIM. Grupo SIM. https://gruposim.eu/blog/como-establecer-objetivos-smart-en-logistica/#:~:text=Para%20la%20gesti%C3%B3n%20eficaz%20de,informaci%C3%B3n%20en%20una%20sola%20herramienta]

#pagebreak()